# Generated by Django 6.1 on 2026-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('diameter', models.FloatField(help_text='km')),
                ('composition', models.TextField()),
                ('moons', models.IntegerField()),
                ('semi_major_axis', models.FloatField(help_text='AU')),
                ('eccentricity', models.FloatField(help_text='Dimensionless')),
                ('inclination', models.FloatField(help_text='Degrees')),
                ('longitude_of_ascending_node', models.FloatField(help_text='Degrees')),
                ('argument_of_periapsis', models.FloatField(help_text='Degrees')),
                ('mean_anomaly', models.FloatField(help_text='Degrees')),
                ('epoch', models.DateTimeField()),
            ],
        ),
    ]
