# Generated by Django 6.1 on 2026-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomy', '0002_planet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=models.ImageField(upload_to='planets/'),
        ),
    ]
